# Generated by Django 5.1.4 on 2025-01-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visualData", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("date", models.DateTimeField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
            ],
        ),
    ]
