# Generated by Django 5.1.4 on 2025-01-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visualData", "0002_recentdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalData",
        ),
        migrations.DeleteModel(
            name="RecentData",
        ),
    ]
